server:
  port: 8020
spring:
  application:
    name: service-consumer-feign
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8765/eureka/
  instance:
    prefer-ip-address: true